name: "Code Quality Checks"

on:
  push:
  pull_request:

jobs:
  Test:
    name: "Code Quality Checks"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install yapf
        run: |
          pip install yapf
      - name: Yapf code formatting checks
        run: |
          yapf -ipr protoplaster/
          test $(git status --porcelain | wc -l) -eq 0 || { git diff; false; }
